{% set name = "pyowm" %}
{% set version = "3.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - pip
    - python=3.9
    - setuptools
  run:
    - python=3.9
    - requests>=2.20.0,<3
    - geojson>=2.3.0,<3
    - PySocks>=1.7.1,<2
    - requests[socks]

